// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX_0g1CckSppAZSRu8F2xrElm7z-WnIs8',
    appId: '1:357185833921:web:48666a4754921f45273d40',
    messagingSenderId: '357185833921',
    projectId: 'asilia-tech',
    authDomain: 'asilia-tech.firebaseapp.com',
    storageBucket: 'asilia-tech.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwWGGf4_qpM0Xy3WQynzJ8pYghr1Kocbo',
    appId: '1:357185833921:android:6d657313d4236755273d40',
    messagingSenderId: '357185833921',
    projectId: 'asilia-tech',
    storageBucket: 'asilia-tech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMSfvvbb-2vLmUuc7qpQcmo6kEjo3Ydg8',
    appId: '1:357185833921:ios:bf4533746727c6e0273d40',
    messagingSenderId: '357185833921',
    projectId: 'asilia-tech',
    storageBucket: 'asilia-tech.appspot.com',
    iosClientId: '357185833921-hn8dt4erj8e5etaroun73u50adqvi2e6.apps.googleusercontent.com',
    iosBundleId: 'com.example.boilerplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMSfvvbb-2vLmUuc7qpQcmo6kEjo3Ydg8',
    appId: '1:357185833921:ios:5bcaca5e1e254d0a273d40',
    messagingSenderId: '357185833921',
    projectId: 'asilia-tech',
    storageBucket: 'asilia-tech.appspot.com',
    iosClientId: '357185833921-3pdb4irrg478k0tvmtg00sjh9099plf9.apps.googleusercontent.com',
    iosBundleId: 'com.example.boilerplate.RunnerTests',
  );
}
